"""empty message

Revision ID: 1bbf2a8b09df
Revises: f268bec11f6c
Create Date: 2020-12-26 13:49:38.986961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbf2a8b09df'
down_revision = 'f268bec11f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('date_retrieved', sa.Date(), nullable=True),
    sa.Column('pos_score', sa.Integer(), nullable=True),
    sa.Column('neg_score', sa.Integer(), nullable=True),
    sa.Column('pos_tweet', sa.String(), nullable=True),
    sa.Column('neg_tweet', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_table')
    # ### end Alembic commands ###
