"""empty message

Revision ID: f268bec11f6c
Revises: 
Create Date: 2020-12-24 21:32:26.811723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f268bec11f6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('date_retrieved', sa.Date(), nullable=True),
    sa.Column('pos_score', sa.Integer(), nullable=True),
    sa.Column('neg_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_table')
    # ### end Alembic commands ###
